[package]
name = "minithesis-rust"
version = "0.1.0"
authors = ["Rik Alexander <rik.de.kort@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
rand_chacha = "*"
sha-1 = "0.9.1"
arrayvec = "0.5"

